personal/urls.py
from django.conf.urls import url
from personal import views


urlpatterns = [
    url(r'^overview/', views.load_tabs_send_mail, name='load-tabs-send-mail'),
    url(r'^home', views.home_page, name='home-page'),
]

ps/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from ps import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('personal.urls', namespace="personal")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
              static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models/photo.py
from django.db import models


def get_image_path(instance, filename):
    return 'user_%s' % filename


class Photo(models.Model):
    pic = models.ImageField(upload_to=get_image_path, null=False, blank=False)
    caption = models.CharField(max_length=200)

    def __str__(self):
        return str(self.caption)

core/models/profile.py
from django.db import models


class Article(models.Model):
    user = models.ForeignKey("core.User")
    pic = models.ForeignKey("core.Photo", null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title


class Career(models.Model):
    SCHOOL = 1
    WORK = 2
    LIFE = 3
    CAREER_TYPE = ((SCHOOL, "School"), (WORK, "Work"), (LIFE, "Life"),)
    user = models.ForeignKey("core.User")
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    pic = models.ForeignKey("core.Photo", null=True, blank=True)
    career_type = models.SmallIntegerField(choices=CAREER_TYPE, default=SCHOOL)
    career_name = models.CharField(max_length=512)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.career_name

    def get_career_type(self):
        return self.CAREER_TYPE[self.career_type - 1][1]

core/models/user.py
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.core.mail import send_mail
from core.managers.user_manager import UserManager, ResetPasswordManager


class User(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField(_('First Name'), max_length=30, blank=True)
    last_name = models.CharField(_('Last Name'), max_length=30, blank=True)
    email = models.EmailField(_('Email Address'), unique=True)
    mobile = models.CharField(_('Mobile'), max_length=30, blank=True)
    created_on = models.DateTimeField(_('Created on'), auto_now_add=True, editable=True)
    is_active = models.BooleanField(_('Active'), default=True)
    # avatar = models.ForeignKey("core.Photo", null=True, blank=True)
    gallery = models.ManyToManyField("Photo", blank=True)
    is_staff = models.BooleanField(
        _('Staff Status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = UserManager()

    class Meta:
        verbose_name = _('User')
        verbose_name_plural = _('Users')

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    # def get_avatar(self):
    #     if self.avatar:
    #         return self.avatar.pic.url

    def is_admin(self):
        if self.groups.filter(name="admin"):
            return True
        return False


class ResetPassword(models.Model):
    user = models.ForeignKey(User)
    key = models.CharField(max_length=128)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now=True)
    modified_on = models.DateTimeField(auto_now_add=True)
    objects = ResetPasswordManager()

personal/views.py
from django.http import HttpResponse
from django.shortcuts import render
from personal.utils import send_mail_async
from django.template.loader import render_to_string
from core.models import User, Career
import json

user = User.objects.get(email="ps.sukhwani@gmail.com")


def home_page(request):
    data = {"user": user}
    return render(request, "home.html", data)


def load_tabs_send_mail(request):
    data = {"user": user,
            "result": False}
    for image in data["user"].gallery.all():
        if image.caption == "about":
            data["about_pic"] = image.pic.url
        if image.caption == "time_line":
            data["time_line_pic"] = image.pic.url
        if image.caption == "contact":
            data["contact_pic"] = image.pic.url
    if request.GET.get("about"):
        data["result"] = True
        return render(request, "about.html", data)
    if request.GET.get("time_line"):
        career_list = []
        career = Career.objects.all().order_by("-start_date")
        for count, career_data in enumerate(career):
            career_dict = {}
            count += 1
            if count % 2 == 0:
                career_dict["right_side"] = career_data
            else:
                career_dict["left_side"] = career_data
            career_list.append(career_dict)
        data["career"] = career_list
        data["result"] = True
        return render(request, "time_line.html", data)
    if request.GET.get("contact"):
        data["result"] = True
        return render(request, "contact.html", data)
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        subject = request.POST.get("subject")
        note = request.POST.get("note")
        email_template = render_to_string('send_email.html', {"name": name, "note": note, "email": email})
        # send_mail_async.apply_async(args=[subject, email_template, email, ["ps.sukhwani@gmail.com"]])
        send_mail_async(subject, email_template, email, ["ps.sukhwani@gmail.com"])
        data = {"sent": True}
        return HttpResponse(json.dumps(data), content_type='application/json')
    return render(request, "base.html", data)

templates/about.html
{% load staticfiles %}

<div class="mdl-grid portfolio-max-width">
    <div class="mdl-cell mdl-cell--12-col mdl-card mdl-shadow--4dp">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">About</h2>
        </div>

        <div class="mdl-card__media">
            <img class="image" src="{{ about_pic }}" border="0" alt="">
        </div>

        <div class="mdl-grid portfolio-copy">
            <h3 class="mdl-cell mdl-cell--12-col mdl-typography--headline">HELLO WORLD</h3>
            <div class="mdl-cell mdl-cell--8-col mdl-card__supporting-text no-padding">
                <p>My name is Pradeep, I’m a Full Stack Developer from Ahmedabad, India. I use web technologies to make
                    web applications. At the moment I’m primarily using Python and Django with JavaScript.</p>
                <p>I have a strong passion for web developing, meeting new people, Sci-Fi and all Scandinavian stuff,
                    such as their travel, photography and nature.</p>
                <p>A few years back I quit my Business and started my journey around the world with only a laptop.</p>
                <p>Always happy to talk to like-minded and interesting people, so if you’re one of them, feel free to <a
                        class="contact" href="javascript:void(0)">contact me</a> anytime:)</p>
            </div>
            <h3 class="mdl-cell mdl-cell--12-col mdl-typography--headline">What I’ve been up to lately:</h3>
            <div class="mdl-cell mdl-cell--8-col mdl-card__supporting-text no-padding">
                <ul>
                    <li>Currently, working in a cool startup called <a href="http://www.nividata.com/" target="_blank">NiviData Consultancy.</a></li>
                    <li>creating this website again with some other UI and cool interface (for the second time)</li>
                    <li>doing an online course on Udacity to touch-up my skills</li>
                    <li>contributing and creating pull requests to open source projects such as <a
                            href="https://github.com/DjangoGirls/tutorial" target="_blank">Django Girls</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<script>
    $(".contact").click(function () {
        $(".mdl-navigation__link:eq(2)").trigger("click");
    });
</script>

templates/base.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="Pradeep Sukhwani">
    <meta name="keywords" content="software developer, developer">
    <meta name="description" content="Full Stack Developer">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <meta name="application-name" content="Pradeep Sukhwani">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-title" content="Pradeep Sukhwani">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">

    <!-- CSS -->
    <link rel="stylesheet"
          href="//fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.grey-pink.min.css">
    <link rel="stylesheet" href="{% static 'css/overview.css' %}">

    <!-- JS -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/material.js' %}"></script>
    <script src="{% static 'js/scrollreveal.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

    <title></title>
</head>
<body>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header mdl-layout__header--waterfall portfolio-header">
        <div class="mdl-layout__header-row portfolio-logo-row">
            <span class="mdl-layout__title">
                <div class="portfolio-logo"></div>
                <span class="mdl-layout__title"><strong>{{ user.first_name }} {{ user.last_name }}</strong></span>
            </span>
        </div>
        <div class="mdl-layout__header-row portfolio-navigation-row mdl-layout--large-screen-only">
            <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
                <a class="mdl-navigation__link" href="{% url 'personal:load-tabs-send-mail' %}?about=True">About</a>
                <a class="mdl-navigation__link" href="{% url 'personal:load-tabs-send-mail' %}?time_line=True">Timeline</a>
                <a class="mdl-navigation__link" href="{% url 'personal:load-tabs-send-mail' %}?contact=True">Contact</a>
            </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer mdl-layout--small-screen-only">
        <nav class="mdl-navigation mdl-typography--body-1-force-preferred-font">
            <a class="mdl-navigation__link" href="{% url 'personal:load-tabs-send-mail' %}?about=True">About</a>
            <a class="mdl-navigation__link" href="{% url 'personal:load-tabs-send-mail' %}?time_line=True">Timeline</a>
            <a class="mdl-navigation__link" href="{% url 'personal:load-tabs-send-mail' %}?contact=True">Contact</a>
        </nav>
    </div>
    <main class="mdl-layout__content">
        <div id="portforlio-content">
        </div>
        <footer class="mdl-mini-footer">{% include "footer.html" %}</footer>
    </main>
</div>
<script>
    $(document).ready(function () {
        $(".mdl-navigation__link").on("click", function () {
            var currentLink = $(this);
            var url = currentLink.attr("href");

            if (currentLink.hasClass("is-active")) {
                return false;
            }
            $.ajax({
                url: url,
                type: "GET",
                success: function (response) {
                    var tabName = currentLink.attr("href").split(" ")[0].slice(11);
                    if (tabName === "about=True") {
                        $(document).find("title").text("About | {{ user.first_name }} {{ user.last_name }}");
                    } else if (tabName === "time_line=True") {
                        $(document).find("title").text("Timeline | {{ user.first_name }} {{ user.last_name }}");
                    } else {
                        $(document).find("title").text("Contact | {{ user.first_name }} {{ user.last_name }}");
                    }
                    $("#portforlio-content").fadeOut("slow", function () {
                        $(this).html(response);
                        $(this).fadeIn("slow");
                    });

                    $(".mdl-navigation__link").removeClass("is-active");
                    currentLink.addClass("is-active");
                },
                error: function () {
                    alert("Something Went wrong");
                }
            });
            return false;
        });
        $(".mdl-navigation__link:first").trigger("click");
    });
</script>
</body>
</html>

templates/contact.html
{% load staticfiles %}

<div class="mdl-grid portfolio-max-width portfolio-contact">
    <div class="mdl-cell mdl-cell--12-col mdl-card mdl-shadow--4dp">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Looking for a developer?</h2>
        </div>
        <div class="mdl-card__media">
            <img class="image" src="{{ contact_pic }}" border="0" alt="">
        </div>
        <div class="mdl-card__supporting-text">
            <div class="align-center">
                <p><strong>Are you looking for a professional, communicative & punctual software engineer with
                    extensive full-stack web development skills for your next project?</strong></p>
                <p>If you have an application you are interested in developing with web technology, I’d love to work
                    with you on it. I’m a full-stack developer which means I can bring your project from concept to
                    completion. I work primarily with Python and Django on the back-end and JavaScript on the
                    front-end but picking up new languages or frameworks isn’t a problem.</p>
                <p>Why not contact me to discuss it further?</p>
            </div>
            <form action="{% url 'personal:load-tabs-send-mail' %}" id="ContactForm" method="POST">
                {% csrf_token %}
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" pattern="[A-Z,a-z, ]*" type="text" name="name" required>
                    <label class="mdl-textfield__label" for="Name">Name</label>
                    <span class="mdl-textfield__error required"><strong>Should I call you John Doe?</strong></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="text" name="email"
                           pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" required>
                    <label class="mdl-textfield__label" for="Email">Email</label>
                    <span class="mdl-textfield__error"><strong>Eg: john.doe@gmail.com</strong></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <input class="mdl-textfield__input" type="text" name="subject" required>
                    <label class="mdl-textfield__label" for="Name">Subject</label>
                    <span class="mdl-textfield__error"><strong>Hmm!! Personal or Professional</strong></span>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    <textarea class="mdl-textfield__input" type="text" rows="5" name="note" required></textarea>
                    <label class="mdl-textfield__label" for="note">Enter note</label>
                    <span class="mdl-textfield__error"><strong>Nothing then just say Howdi!</strong></span>
                </div>
                <p>
                    <button class="mdl-button mdl-js-button
                    mdl-button--raised mdl-js-ripple-effect mdl-button--accent" type="submit">Send
                    </button>
                    <div class="mdl-spinner mdl-js-spinner"></div>
                </p>
            </form>
        </div>
    </div>
</div>
<script>
    $(document).ready(function () {
        $(".mdl-textfield__input").focus(function () {
            $(this).parent().addClass('is-focused');
            $(this).parent().removeClass('is-invalid');
        });

        $(".mdl-textfield__input").blur(function () {
            if (!this.value) {
                $(this).parent().removeClass('is-focused');
                $(this).prop('required', true);
                $(this).parent().addClass('is-invalid');
            }
        });
        $("#ContactForm").submit(function () {
            var form = $(this);
            var url = form.attr("action");
            var btn = form.find("button");
            $.ajax({
                url: url,
                type: "POST",
                data: $(form).serialize(),
                beforeSend: function () {
                    btn.text("Sending...");
                    btn.attr("disabled", "disabled");
                    componentHandler.upgradeElement($('.mdl-js-spinner')[0]);
                    $(".mdl-spinner").addClass("is-active");
                },
                success: function (response) {
                    if (response.sent) {
                        $(document).find("title").text("Success | Pradeep Sukhwani");
                        $(".mdl-card__title-text").html("Success");
                        $(".mdl-card__supporting-text").html('<img class="align-center"' +
                            'src="{% static 'images/success.png' %}"><h1 class="align-center">HUZZAH!</h1>' +
                            '<p class="align-center">Your message just arrived in my inbox. Talk to you soon.</p>');
                    } else {
                        alert("Something Went wrong try reloading the page!");
                    }
                },
                error: function () {
                    alert("Something went wrong");
                }
            });
            return false;
        });
    });
</script>

templates/home.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="Pradeep Sukhwani">
    <meta name="keywords" content="software developer, developer">
    <meta name="description" content="Full Stack Developer">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <meta name="application-name" content="Pradeep Sukhwani">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="apple-mobile-web-app-title" content="Pradeep Sukhwani">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-touch-icon.png' %}">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="theme-color" content="#ffffff">

    <!-- CSS -->
    <link rel="stylesheet"
          href="//fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="//code.getmdl.io/1.3.0/material.grey-pink.min.css">
    <link rel="stylesheet" href="{% static 'css/home_page.css' %}">

    <!-- JS -->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/home.js' %}"></script>
    <title>Home | {{ user.first_name }} {{ user.last_name }}</title>
</head>
<body>
<div id="portforlio-content">
    <div id="portforlio-content-inner">
        <div class="content-container">
            <h2 class="content"><span class="content-font">P | S</span></h2>
            <a class="main-site-link" href="{% url 'personal:load-tabs-send-mail' %}">ENTER<span></span></a>
        </div>
    </div>
</div>
<script>
</script>
</body>
</html>

templates/send_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Enquiry From {{ name }}</title>
</head>
<body>
    Email Address: {{ email }}
    <br><br>
    {{ note }}
</body>
</html>

templates/time_line.html
{% load staticfiles %}

<div class="mdl-grid portfolio-max-width">
    <div class="mdl-cell mdl-cell--12-col mdl-card mdl-shadow--4dp">
        <div class="mdl-card__title">
            <h2 class="mdl-card__title-text">Timeline</h2>
        </div>

        <div class="mdl-card__media">
            <img class="image" src="{{ time_line_pic }}" border="0" alt="">
        </div>

        <div class="timeline-wrapper">
            <div class="mdl-cell mdl-cell--12-col mdl-card__supporting-text no-padding">
            <section class="timeline">
                <div class="container">
                    {% for data in career %}
                        {% if data.left_side %}
                            <div class="timeline-item">
                                <div class="timeline-img"></div>
                                <div class="timeline-content timeline-card js--fadeInLeft">
                                    <div class="timeline-img-header">{{ data.left_side.pic.pic.url }}
                                        <h2>{{ data.left_side.career_name }}</h2>
                                    </div>
                                    <div class="career-type">
                                        {{ data.left_side.get_career_type }}
                                    </div>
                                    <div class="date">{% if not data.left_side.end_date %} Since
                                        {{ data.left_side.start_date|date:"M Y" }} {% else %}
                                        {{ data.left_side.start_date|date:"M Y" }}{% endif %}</div>
                                    <p>{{ data.left_side.description|safe }}</p>
    {#                                <a class="bnt-more" href="javascript:void(0)">More</a>#}
                                </div>
                            </div>
                        {% else %}
                            <div class="timeline-item">
                                <div class="timeline-img"></div>
                                <div class="timeline-content timeline-card js--fadeInRight">
                                    <div class="timeline-img-header">
                                        <h2>{{ data.right_side.career_name }}</h2>
                                    </div>
                                    <div class="career-type">
                                        {{ data.right_side.get_career_type }}
                                    </div>
                                    <div class="date">{% if not data.right_side.end_date %} Since
                                        {{ data.right_side.start_date|date:"M Y" }} {% else %}
                                        {{ data.right_side.start_date|date:"M Y" }}{% endif %}</div>
                                    <p>{{ data.right_side.description|safe }}</p>
{#                                    <a class="bnt-more" href="javascript:void(0)">More</a>#}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </section>
        </div>
        </div>
    </div>
</div>